### ISSUE TITLE
How to get the secondary screen touch event

### ISSUE THREAD

**Issue by chenyayun** [commonsguy/cwac-presentation#10]
I want to touch both local screen and secondary screen. I have try to run the demo app, and connect a mouse. But I cannot move the mouse to the secondary screen.

Is anybody know why? 

Thankyou for read!

**Comment by commonsguy** [comment]
First, this is an issue tracker, not a support board. Please follow the instructions in [the documentation](https://github.com/commonsguy/cwac-presentation#questions) for getting support.

Second, your concern has nothing to do with this library, or with any library.

Third, what you want is not supported by Android.
