### ISSUE TITLE
secondary screen display issue

### ISSUE THREAD

**Issue by chenyayun** [commonsguy/cwac-presentation#12]
Hello, I use the PresentationService to display a view on a screen(can touch).
When I touch the view's child view to move position, but the screen has smear,

When I change the targetSdkVersion to "17", it display with no issue.

Do you know why, thanks!

**Comment by chenyayun** [comment]
I use the latest version code.

**Comment by commonsguy** [comment]
This is an issue tracker. It is not a support forum. Please use [the support resources outlined in the project `README`](https://github.com/commonsguy/cwac-presentation#questions).

The SDK's `Presentation` class, and my `PresentationService`, are not designed to work on touchscreens. I have no means of supporting your use case, let alone reproducing your problem. Sorry!
