### ISSUE TITLE
Presentation surface of presentation service is destroyed when terminating the parent application

### ISSUE THREAD

**Issue by Artalizian** [commonsguy/cwac-presentation#13]
This problem occurs when an app contains both an activity and a presentation service. When terminating the activity(app) then the presentation service's surface is destroyed.

I've observed this problem in my own application but it also occurs with the demoService application.
Android OS version: 7.0

Bringing the app to the background works correctly, only destroying the app triggers this behavior.
The presentation service is automatically restarted after 1 sec, after which it works correctly.

Error captured with adb logcat
`12-20 15:31:20.326  3713  7220 I WindowManager_SurfaceController: Destroying surface Surface(name=com.android.systemui/com.android.systemui.recents.RecentsActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2840 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1070 com.android.server.wm.WindowState.destroyOrSaveSurface:2561 com.android.server.wm.AppWindowToken.destroySurfaces:412 com.android.server.wm.AppWindowToken.destroySurfaces:376 com.android.server.wm.AppWindowToken.notifyAppStopped:456 com.android.server.wm.WindowManagerService.notifyAppStopped:5199`

**Comment by commonsguy** [comment]
What **exactly** do you mean by "terminating the activity(app)" and "destroying the app"? Also, what device are you testing on, and are you testing with an actual external display or with the simulated secondary display that you can enable from Developer Options?

IOW, as is outlined in [the contribution guidelines](https://github.com/commonsguy/cwac-presentation/blob/master/CONTRIBUTING.md#contributing-bug-reports), I need the steps to take to try to reproduce the problem.

**Comment by Artalizian** [comment]
With terminating / destroying I mean closing the app as in pressing the Overview button and then swiping the app to the right to close it.
Using a Samsung Galaxy S7
This problem was tested using a simulated display.

**Comment by commonsguy** [comment]
OK, I will take a look at this in a couple of days. In the meantime, you could try making your service be a foreground service, if it is not one already, and see if that helps. You will need this for Android 8.0+ anyway, and my guess is that this is not a problem with the library but rather a problem of the service being destroyed.

**Comment by commonsguy** [comment]
I was able to reproduce the problem, and my guess seems to be correct: using a foreground service clears up the flawed behavior (caused by the process being terminated). FWIW, the `v0.5.1`-tagged source has a version of `demoService` that uses a foreground service.

Thanks for pointing out the issue!

**Comment by Artalizian** [comment]
Thanks for quickly looking into this and providing a fix for the problem!
