### ISSUE TITLE
Recycleview list item is not scrolling on external display.Touch is blocking.

### ISSUE THREAD

**Issue by NarendraKr** [commonsguy/cwac-presentation#18]

**Comment by commonsguy** [comment]
External displays do not provide touch input. External displays are for output only.

**Comment by NarendraKr** [comment]
https://drive.google.com/file/d/1VQO6QB8hOWURbLrQQK5GSIDuhAapqWFi/view?usp=sharing

This is code.I am using it.

**Comment by NarendraKr** [comment]
> External displays do not provide touch input. External displays are for output only.
> 
> If you have evidence that it is my library that is somehow doing something wrong, please provide an example app that demonstrates the problem!

Thanks

**Comment by commonsguy** [comment]
Can you explain, in detail, why you think my library is doing something wrong? For example, do you have touch input working when using this external display in other ways?

**Comment by NarendraKr** [comment]
No issue in your library.I fixed the issue.I am using VideoView and it's working fine.Now i can take input from external display.
