### ISSUE TITLE
PresentationService DOES require TYPE_SYSTEM_ALERT / SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by alenz316** [commonsguy/cwac-presentation#6]
https://github.com/commonsguy/cwac-presentation/issues/4 is no longer true for Android 5.1+.The `WindowManager.LayoutParams.TYPE_SYSTEM_ALERT` flag and the `android.permission.SYSTEM_ALERT_WINDOW` are required for the PresentationService for 22+.

**Comment by commonsguy** [comment]
Yeah, I stumbled into this myself yesterday. It's rather frustrating, as there is no good reason for those requirements, since we are not displaying on the primary display. I'll be working on this shortly. Thanks!

**Comment by commonsguy** [comment]
`TYPE_TOAST` works on 5.0 and 5.1 without any particular permissions. I'll be releasing an update that uses this shortly.

**Comment by commonsguy** [comment]
Addressed in v0.4.5. Thanks!
