### ISSUE TITLE
gradle-wrapper.jar is missed in this repository

### ISSUE THREAD

**Issue by vbauer** [commonsguy/cwac-presentation#7]

**Comment by commonsguy** [comment]
@vbauer That is intentional. **Never** use a `gradle-wrapper.jar` unless you trust the provider of that JAR with the entire contents of your hard drive and the entire contents of any network resources that you can access. You should not trust me with those things.

**Comment by vbauer** [comment]
@commonsguy Similarly, you can use some library or plugin that does something destructive. Just want to notify you that it is impossible to build this project with Gradle 2.10 (that was installed by default on my local machine)

**Comment by commonsguy** [comment]
> Similarly, you can use some library or plugin that does something destructive.

Plugins are a similar issue. Libraries, at least as I would use the term, affect user devices, not developer machines, as the code for the library does not run on a developer machine.

> Just want to notify you that it is impossible to build this project with Gradle 2.10

[`gradle-wrapper.properties`](https://github.com/commonsguy/cwac-presentation/blob/master/gradle/wrapper/gradle-wrapper.properties) calls for 2.2.1 at the moment, which is pretty old. Android Studio will use `gradle-wrapper.properties` without `gradle-wrapper.jar`. If you are looking to do command-line builds, either add a full Gradle Wrapper to your local copy of the project (leaving the existing `gradle-wrapper.properties` file), or install Gradle 2.2.1, or poke at the Gradle build settings until you get a build that works.

You can track issue #8 for my work to upgrade the build configuration for this project.
